packages:
  nexxtender:
    url: https://github.com/geertmeersman/nexxtender
    files: [
        config/ha_addon.yaml, # how you run esphome: ha_addon, docker, local,
        config/mqtt/false.yaml, # mqtt config: true.yaml or false.yaml
        config/wifi.yaml, # only include if you need wifi. In case of ethernet, add the component manually
      ]
    refresh: 0s
substitutions:
  ## Uncomment and modify when you want to use a different device name.
  # device_name: nexxtender
  # friendly_name: Nexxtender
  ## Uncomment and modify when you want to use a different threshold.
  # charging_mode_eco_threshold: "8"      # Single phase (6A + 2 margin)
  # charging_mode_eco_bi_threshold: "14"  # Bi-phase (12A + 2 margin)
  # charging_mode_eco_tri_threshold: "20" # Tri-phase (18A + 2 margin)
  # slider_max_car_charging_speed: "32"     # The max value of the slider for the maximum car charging speed slider, default set to 32
  # slider_max_available_capacity: "40"     # The max value of the slider for the maximum available capacity slider, default set to 40
  # slider_max_peak_consumption_limit: "40" # The peak consumption limit for the slider (in amperes, typically 16-40A). WARNING: Incorrect values may cause circuit breaker trips or reduced charging performance. This value is usually configured by your installer.
  # min_charging_value: "6" # The minimal charging value, used for the slider configs
  # slider_max_offloading_minimum: "32" # The max offloading minimum value
  # slider_min_offloading_minimum: "6" # The min offloading minimum value
