esphome:
  min_version: 2024.2.0
  name: ${device_name}
  friendly_name: ${friendly_name}
  includes:
    # Calculate the path using the calculate_esphome_package_path.py script
    - .esphome/packages/fe6cda15/config/nexxtender_packages/nexxtender.h
