text_sensor:
  - platform: template
    name: ${prefix_text_sensor}Code version
    id: nexxtender_code_version
    icon: mdi:file-certificate
    entity_category: diagnostic
    lambda: |-
      return {"v5.2.1"};
