packages:
  esp: !include nexxtender_packages/esp.yaml
  esphome: !include nexxtender_packages/esphome.local.yaml
  mqtt: !include nexxtender_packages/mqtt_true.yaml
  #webserver: !include nexxtender_packages/webserver.yaml # secret esphome_admin_password required
  api: !include nexxtender_packages/api.yaml # secrets esphome_admin_password, wifi_ssid, wifi_password & esphome_api_key required
  time: !include nexxtender_packages/time.yaml
  ble: !include nexxtender_packages/ble.yaml # secrets nexxtender_mac & nexxtender_passkey required
  device_information: !include nexxtender_packages/device_information.yaml
  generic_data: !include nexxtender_packages/generic_data.yaml
  charging_car_data: !include nexxtender_packages/charging_car_data.yaml
  charging_grid_data: !include nexxtender_packages/charging_grid_data.yaml
  charging_basic_data: !include nexxtender_packages/charging_basic_data.yaml
  charging_advanced_data: !include nexxtender_packages/charging_advanced_data.yaml
  version: !include nexxtender_packages/version.yaml
  #transactions: !include nexxtender_packages/transactions.yaml
  #diagnostics: !include nexxtender_packages/diagnostics.yaml
  #dev_debug: !include nexxtender_packages/dev_debug.yaml

substitutions:
  # device_name: nexxtender
  # friendly_name: Nexxtender
  # charging_mode_eco_mono_threshold: "8"
  # charging_mode_eco_bi_threshold: "14"
  # charging_mode_eco_tri_threshold: "20"
  # slider_max_car_charging_speed: "32"
  # slider_max_available_capacity: "40"
  # slider_max_peak_consumption_limit: "40" # The peak consumption limit for the slider (in amperes, typically 16-40A). WARNING: Incorrect values may cause circuit breaker trips or reduced charging performance. This value is usually configured by your installer.
  # min_charging_value: "6" # The minimal charging value, used for the slider configs
  # slider_max_offloading_minimum: "32"
  # slider_min_offloading_minimum: "6"
