wifi:
  ssid: !secret wifi_ssid # WiFi network SSID (from secrets.yaml)
  password: !secret wifi_password # WiFi password (from secrets.yaml)
  fast_connect: true # Skip scanning for best AP, useful for fixed networks
  ap: # Access Point fallback if WiFi fails
    ssid: ${device_name} - FB # AP SSID (uses device_name variable)
    password: !secret esphome_admin_password # AP password
  on_connect: # Actions when WiFi connects successfully
    then:
      - lambda: |- # Inline C++ code, et global variable to true
          id(g_wifi_connected) = true;
  on_disconnect: # Actions when WiFi disconnects, set global variable to false
    then:
      - lambda: |-
          id(g_wifi_connected) = false;

# Captive portal: allows connecting to ESP via AP for configuration if WiFi fails
captive_portal:
